# build, test, and ftp deploy a jekyll site
name: Publish Website on Cpanel
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      BASEURL: ''
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{secrets.FTP_SERVER}}
          username: ${{secrets.FTP_USERNAME}}@{{secrets.FTP_SERVER}}
          password: ${{secrets.FTP_PASSWORD}}
          protocol: ftps
          port: 21
