name: Publish Website on Cpanel
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      BASEURL: ''
    steps:
      - name: Get latest code
      - uses: actions/checkout@v2
      
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.saleem-group.com
          username: saleemfx@dashboard.saleemfx.com
          password: L-ZqTJjL?#}^
          protocol: ftps
          port: 21
